---
title: "Lectures"
---

## Lecture Slides

Lecture slides are available as self-contained `.html` files made with RevealJS from a Quarto `.qmd` file. You can choose to print these to a PDF document by using the "PDF Export Mode" in the Tools menu accessed via the settings button in the lower left-hand side of the page. You are also welcome to directly download the `.qmd` file and supporting data/images/etc. from the GitHub repository. Slides are organized by week and combine Tuesday and Wednesday's lectures.

Links become active as the materials for each week are posted.

<!-- Template for each week once slides are posted:

- [Week N GitHub Repository](https://github.com/astrezhnev/ps812/tree/main/slides/weekN/)
- [Week N `.html` slides](https://www.antonstrezhnev.com/ps812/slides/weekN/weekN_topic.html)

-->

### Week 1: Introduction and Foundations of Probability

- [Week 1 Github Repository](https://github.com/astrezhnev/ps812/tree/main/slides/week1/)
- [Week 1 `.html` slides](https://www.antonstrezhnev.com/ps812/slides/week1/week1_intro_and_review.html)

### Week 2: Conditional Probability and Independence

- [Week 2 Github Repository](https://github.com/astrezhnev/ps812/tree/main/slides/week2/)
- [Week 2 `.html` slides](https://www.antonstrezhnev.com/ps812/slides/week2/week2_conditional_probability.html)
- [Illustrating conditional probability](https://www.antonstrezhnev.com/ps812/slides/week2/ces_conditioning_app.html) - How does the distribution of Party ID shift as you condition on observed policy preferences? (RShiny app using data from the Cooperative Election Study 2025)
- [Illustrating Bayes' rule with BISG](https://www.antonstrezhnev.com/ps812/slides/week2/bisg_app.html) - Can we predict an individual's race/ethnicity from geolocation and surname frequency data (RShiny app using the Census Bureau surname list and the 2020 Census)

### Week 3: Random Variables and Distributions

*To be posted*

### Week 4: Joint Distributions and Expectation

*To be posted*

### Week 5: Variance, Covariance, and Conditional Expectation

*To be posted*

### Week 6: Estimation: Part 1

*To be posted*

### Week 7: Estimation: Part 2

*To be posted*

### Week 8: Confidence Intervals and Hypothesis Testing

*To be posted*

### Week 9: Introduction to Regression

*To be posted*

### Week 10: Inference for Regression

*To be posted*

### Week 11: Interpreting Regressions

*To be posted*

### Week 12: Regression Wrap-up

*To be posted*

### Week 13: Weighting Estimators

*To be posted*

### Week 14: Preview: Causal inference

*To be posted*
